version: 2
updates:
# Scanner (npm and Docker)
  - package-ecosystem: "npm"
    directory: "/src/scanner/" # Location of package manifests
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "production"


  - package-ecosystem: "docker" 
    directory: "/src/scanner/"
    schedule:
      interval: "weekly"

# Core (npm and Docker)
  - package-ecosystem: "npm" 
    directory: "/src/core/" 
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "production"


  - package-ecosystem: "docker" 
    directory: "/src/core/" 
    schedule:
      interval: "weekly"

# Backend (go and Docker)
  - package-ecosystem: "docker"
    directory: "/src/backend/" 
    schedule:
      interval: "weekly"

  - package-ecosystem: gomod
    directory: /src/backend/src/
    schedule:
      interval: weekly
