services:
  node-headless:
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    # use Dockerfile.dev

    ports:
      - 3030:3030
    restart: always
    environment:
      - ENDPOINT
      - SCANNER_TOKEN
      - SELF_SIGNED
    # https://stackoverflow.com/questions/50662388/running-headless-chrome-puppeteer-with-no-sandbox/53975412#53975412
    security_opt:
      - seccomp=./chrome.json
