# Filename: Dockerfile
FROM node:21-bullseye-slim
WORKDIR /app

# Copy package.json
COPY package.json yarn.lock* ./

# Install NPM dependencies for function
RUN yarn install

ADD src ./src

# We don't need the standalone Chromium
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

# Copy plugin
ADD fihnjjcciajhdojfnbdddfaoknhalnja ./fihnjjcciajhdojfnbdddfaoknhalnja

# Expose app
EXPOSE 3000
# Run app
CMD ["yarn", "run", "start"]