name: scanner.dev-build-push

on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - 'src/scanner/**'
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/scanner 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=dev,enable=${{ endsWith(github.ref, '-dev') }}
            type=sha

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: src/scanner
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
