name: Scanner Mocha tests
on: 
  workflow_dispatch: # manual
  push:
    branches-ignore:
      - 'main'
    paths:
      - 'src/scanner/**'
  pull_request:
    
jobs:
  scanner-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'
      - name: Start backend
        run: ./scripts/setup-scanner-test-env.sh

      - name: Mocha run
        run: ./scripts/run-scanner-test.sh